version: "2.3"


services:
  main:
    build:
      context: .
      args:
        MODE: dev
    volumes:
      - ./:/src/
    depends_on:
      - db
    environment:
      - PYTHONPATH=.

  db:
    image: postgres:11
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
